"""
Django settings for dalanid project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/


def _flag(name, default=False):
    """Read a boolean from the environment.

    Every demonstration affordance in this project is gated on one of these.
    They default to off so that the committed configuration is the safe one,
    and a deployment that sets nothing gets the hardened behaviour.
    """
    raw = os.environ.get(name)
    if raw is None:
        return default
    return raw.strip().lower() in {"1", "true", "yes", "on"}


# Enables the demonstration affordances as a group: the unprotected baseline
# endpoint, key issuance over HTTP, and precise refusal codes. Required by
# evaluate.py, which drives a running server, and by the test suite. Never set
# this in a deployment.
DALANID_DEMO = _flag("DALANID_DEMO")

# SECURITY WARNING: keep the secret key used in production secret!
# Supplied by the environment in any real deployment. The fallback exists so
# the demonstration runs from a clean checkout without setup, and is marked
# insecure so it cannot be mistaken for a real key.
SECRET_KEY = os.environ.get(
    "DALANID_SECRET_KEY",
    "django-insecure-development-fallback-do-not-deploy-with-this-value",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _flag("DALANID_DEBUG")

# DEBUG is off by default, so the hosts the demonstration actually uses have
# to be named explicitly or Django refuses every request.
ALLOWED_HOSTS = [
    h.strip()
    for h in os.environ.get(
        "DALANID_ALLOWED_HOSTS", "localhost,127.0.0.1,[::1]"
    ).split(",")
    if h.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'identity',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'dalanid.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'dalanid.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        # SQLite serialises writers on a single lock. Write-ahead logging
        # plus a busy timeout lets concurrent disclosure requests queue for
        # the audit append instead of failing immediately.
        'OPTIONS': {
            'timeout': 20,
            'init_command': 'PRAGMA journal_mode=WAL; PRAGMA synchronous=NORMAL;',
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}


# --- DalanID configuration -------------------------------------------------

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [],
    "DEFAULT_PERMISSION_CLASSES": [],
    "UNAUTHENTICATED_USER": None,
}

# The unprotected full-record endpoint is a measurement baseline, not a
# feature. It stays off unless deliberately enabled for evaluation runs.
DALANID_ALLOW_FULL_RECORD = _flag("DALANID_ALLOW_FULL_RECORD", DALANID_DEMO)

# The React prototype runs on the Vite dev server during development.
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]
CORS_ALLOW_HEADERS = [
    "accept",
    "content-type",
    "x-context-key",
]

# Key issuance over HTTP is a demonstration affordance; see views.issue_key.
DALANID_ALLOW_KEY_ISSUANCE = _flag("DALANID_ALLOW_KEY_ISSUANCE", DALANID_DEMO)

# Ceilings on runtime-created contexts, so extensibility cannot be used to
# reconstruct the unprotected record. See identity/serializers.py.
DALANID_MAX_CONTEXT_FIELDS = 5
DALANID_MAX_CONTEXT_SENSITIVITY = 12

# Return the precise refusal code to callers instead of a collapsed one.
# Useful in development and for the evaluation harness; must be False in
# deployment, where distinguishing RP_UNKNOWN from a bad signature would let
# an attacker enumerate registered organisations. See identity/keys.py.
DALANID_VERBOSE_REFUSALS = _flag("DALANID_VERBOSE_REFUSALS", DALANID_DEMO)

# Subject tokens are obtained through /auth/login and /auth/verify. This flag
# re-opens the older unauthenticated route and must stay False outside the
# evaluation harness.
DALANID_ALLOW_UNAUTHENTICATED_SUBJECT_TOKEN = _flag(
    "DALANID_ALLOW_UNAUTHENTICATED_SUBJECT_TOKEN"
)

# Django's default hasher is deliberately slow, which is correct in production
# and pure overhead in the test suite. Tests override this; see manage.py.
PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
]
if os.environ.get("DALANID_FAST_HASHING"):
    PASSWORD_HASHERS = ["django.contrib.auth.hashers.MD5PasswordHasher"]
