# Generated by Django 6.1.1 on 2026-09-04 04:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('label', models.CharField(max_length=128)),
                ('sensitivity', models.PositiveSmallIntegerField(default=1, help_text='1 (low) to 5 (high). Used for reporting, not enforcement.')),
                ('derivation', models.CharField(choices=[('none', 'Disclose raw value'), ('age_band', 'Disclose age band only'), ('year_only', 'Disclose year only'), ('presence', 'Disclose presence, not content')], default='none', max_length=16)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='AuditEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(unique=True)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('relying_party_slug', models.CharField(blank=True, max_length=64)),
                ('context_slug', models.CharField(blank=True, max_length=64)),
                ('citizen_public_id', models.CharField(blank=True, max_length=64)),
                ('disclosed_codes', models.JSONField(default=list)),
                ('withheld_count', models.PositiveSmallIntegerField(default=0)),
                ('outcome', models.CharField(default='disclosed', max_length=32)),
                ('reason_code', models.CharField(blank=True, max_length=48)),
                ('previous_hash', models.CharField(blank=True, max_length=64)),
                ('entry_hash', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name_plural': 'audit entries',
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.SlugField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['public_id'],
            },
        ),
        migrations.CreateModel(
            name='Context',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('tier', models.CharField(default='Standard', max_length=32)),
                ('purpose', models.TextField(blank=True, help_text='The stated purpose this context exists to serve. Recorded so that disclosure can be audited against declared purpose.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='ContextAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identity.attribute')),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identity.context')),
            ],
            options={
                'unique_together': {('context', 'attribute')},
            },
        ),
        migrations.AddField(
            model_name='context',
            name='attributes',
            field=models.ManyToManyField(related_name='contexts', through='identity.ContextAttribute', to='identity.attribute'),
        ),
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('granted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identity.context')),
            ],
        ),
        migrations.CreateModel(
            name='RelyingParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('signing_secret', models.CharField(max_length=128)),
                ('can_create_contexts', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('grants', models.ManyToManyField(related_name='relying_parties', through='identity.Grant', to='identity.context')),
            ],
            options={
                'verbose_name_plural': 'relying parties',
                'ordering': ['slug'],
            },
        ),
        migrations.AddField(
            model_name='grant',
            name='relying_party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identity.relyingparty'),
        ),
        migrations.AddField(
            model_name='context',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contexts_created', to='identity.relyingparty'),
        ),
        migrations.CreateModel(
            name='CitizenAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=256)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identity.attribute')),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='identity.citizen')),
            ],
            options={
                'unique_together': {('citizen', 'attribute')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='grant',
            unique_together={('relying_party', 'context')},
        ),
    ]
