# Generated by Django 6.1.1 on 2026-09-04 06:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='access_secret',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.CreateModel(
            name='UsedKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jti', models.CharField(max_length=64, unique=True)),
                ('relying_party_slug', models.CharField(blank=True, max_length=64)),
                ('used_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['-used_at'],
                'indexes': [models.Index(fields=['expires_at'], name='identity_us_expires_43485a_idx')],
            },
        ),
    ]
