# Generated by Django 6.1.1 on 2026-09-04 08:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_citizen_access_secret_usedkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='failed_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='citizen',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='citizen',
            name='password_hash',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='citizen',
            name='totp_secret',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.CreateModel(
            name='UsedTotpCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8)),
                ('time_step', models.BigIntegerField()),
                ('used_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_totp_codes', to='identity.citizen')),
            ],
            options={
                'ordering': ['-used_at'],
                'unique_together': {('citizen', 'time_step', 'code')},
            },
        ),
    ]
