# Generated by Django 6.1.1 on 2026-09-04 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0003_citizen_failed_attempts_citizen_locked_until_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relyingparty',
            name='algorithm',
            field=models.CharField(default='ed25519', max_length=16),
        ),
        migrations.AddField(
            model_name='relyingparty',
            name='private_key',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='relyingparty',
            name='public_key',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='relyingparty',
            name='signing_secret',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
